version: "3"

services:

  prod:
    image: prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    hostname: prod
    volumes:
      - yarn:/home/node/.cache/yarn
    environment:
      - SITE_URL=https://vue-by-example.firebaseapp.com
      - FUNC_URL=https://us-central1-vue-by-example.cloudfunctions.net
    tty: true

volumes:
  yarn:
