version: "3"

services:

  default:
    image: default
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "5000:5000"
    volumes:
      - yarn:/home/node/.cache/yarn
    tty: true

  dev:
    image: dev  # shyamchen/dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - yarn:/home/node/.cache/yarn
    tty: true

  prod:
    image: prod  # shyamchen/prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - yarn:/home/node/.cache/yarn
    tty: true

volumes:
  yarn:
