version: "3"

services:

  develop:
    image: develop
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - yarn:/home/node/.cache/yarn
    tty: true

  staging:
    image: staging
    build:
      context: .
      dockerfile: Dockerfile.staging
    volumes:
      - yarn:/home/node/.cache/yarn
    tty: true

  master:
    image: master
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - yarn:/home/node/.cache/yarn
    tty: true

volumes:
  yarn:
