version: "3"

services:

  default:
    image: default
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - yarn:/home/node/.cache/yarn
    tty: true

  dev:
    image: dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - yarn:/home/node/.cache/yarn
    tty: true

  stage:
    image: stage
    build:
      context: .
      dockerfile: Dockerfile.stage
    volumes:
      - yarn:/home/node/.cache/yarn
    tty: true

  prod:
    image: prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - yarn:/home/node/.cache/yarn
    tty: true

volumes:
  yarn:
